const express = require('express');
const router = express.Router();
const authRoutes = require('./authRoutes');
const companyRoutes = require('./companyRoutes');
const subscriptionRoutes = require('./subscriptionRoutes');
const notificationRoutes = require('./notificationRoutes');
const enquiryRoutes = require('./enquiryRoutes');
const faceRoutes = require('./face.routes');
const authEmployeeRoutes = require('./authEmployee.routes');
const dashboardRoutes = require('./dashboardRoutes');
const subscriptionPlanRoutes = require('./subscriptionPlanRoutes');
const attendanceRoutes = require('./attendanceRoutes');
const assetRoutes = require('./assetRoutes');
const leaveRoutes = require('./leaveRoutes');
const companyDashboardRoutes = require('./companyDashboardRoutes');
const gatePassRoutes = require('./gatePassRoutes');
const weeklyOffRoutes = require('./weeklyOffRoutes');
const visitorRoutes = require('./visitorRoutes');
const documentRoutes = require('./documentRoutes');
const courierRoutes = require('./courierRoutes');

router.use('/auth', authRoutes);
router.use('/companies', companyRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/subscription-plans', subscriptionPlanRoutes);
router.use('/notifications', notificationRoutes);
router.use('/enquiries', enquiryRoutes);
router.use('/faces', faceRoutes);
router.use('/auth-employee', authEmployeeRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/assets', assetRoutes);
router.use('/leaves', leaveRoutes);
router.use('/company-dashboard', companyDashboardRoutes);
router.use('/gate-passes', gatePassRoutes);
router.use('/weekly-off', weeklyOffRoutes);
router.use('/visitors', visitorRoutes);
router.use('/documents', documentRoutes);
router.use('/couriers', courierRoutes);

module.exports = router;
